version: "2"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - wepink
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    expose:
      - 80
    networks:
      - wepink
      - nginx-proxy
    environment:
      VIRTUAL_HOST: wepink.localhost
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_TEMP_DIR', ABSPATH . 'wp-content/TEMP');
        define('DB_CHARSET', 'utf8');

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    networks:
      - wepink
      - nginx-proxy
    environment:
      VIRTUAL_HOST: phpmyadmin.wepink.localhost
      PMA_USERNAME: wordpress
      PMA_PASSWORD: wordpress
      PMA_HOSTS: db
      UPLOAD_LIMIT: 1000M
      PHP_MAX_INPUT_VARS: 10000

volumes:
  db_data:

networks:
  wepink:
  nginx-proxy:
    external: true
    name: proxy_default
